<?php

namespace Database\Seeders;

use App\Models\Data;
use App\Models\Role;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run()
    {
        Role::create(['name' => 'kepala_sekolah']);
        Role::create(['name' => 'guru']);
        Role::create(['name' => 'siswa']);

        User::create([
            'name' => 'adminastri',
            'email' => 'adminastri@gmail.com',
            'password' => bcrypt('adminastri'),
            'role_id' => 1
        ]);

        User::create([
            'name' => 'mahasiswaastri',
            'email' => 'mahasiswaastri@gmail.com',
            'password' => bcrypt('mahasiswaastri'),
            'role_id' => 2
        ]);

        User::create([
            'name' => 'pengunjungastri',
            'email' => 'pengunjungastri@gmail.com',
            'password' => bcrypt('pengunjungastri'),
            'role_id' => 3
        ]);

        DB::table('data')->insert([
            [
                'NIK' => '1234567890',
                'NamaLengkap' => 'John Doe',
                'AlamatDomisili' => 'Jalan Raya No. 123',
                'JenisKelamin' => 'Laki-laki',
                'PendidikanTerakhir' => 'SMA',
                'Jurusan' => 'IPA',
                'TanggalPengesahan' => '2023-06-28',
                'Status' => 'BelumTerverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '0987654321',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'BelumTerverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '09876543211',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'BelumTerverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '09876543212',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'BelumTerverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '09876543213',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'BelumTerverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '09876543214',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'BelumTerverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '09876543215',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'BelumTerverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '09876564321',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'BelumTerverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '09876544321',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'BelumTerverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '09876543221',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'BelumTerverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '098765124321',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'BelumTerverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '098765234321',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'BelumTerverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '098765423321',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'BelumTerverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '0987165423321',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'Terverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '120987612154321',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'Terverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '098765431221',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'Terverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '0987654312421',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'Terverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '098765464321',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'Terverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '0987654232321',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'Terverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '098765224321',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'Terverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '09876542212321',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'Terverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '0987651243421',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'Terverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '124234252',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'Terverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '098765241124321',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'Terverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '09876511214321',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'Terverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '09876541111321',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'Terverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '098765554544321',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'BelumTerverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '0987652342614321',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'BelumTerverifikasi',
                'alasan_penolakan' => null,
            ],
            [
                'NIK' => '0987612154321',
                'NamaLengkap' => 'Jane Smith',
                'AlamatDomisili' => 'Jalan Baru No. 456',
                'JenisKelamin' => 'Perempuan',
                'PendidikanTerakhir' => 'S1',
                'Jurusan' => 'Ekonomi',
                'TanggalPengesahan' => '2023-06-29',
                'Status' => 'BelumTerverifikasi',
                'alasan_penolakan' => null,
            ]
        ]);
    }
}
